#	MAKEFILE for the Cabezon compiler
#
#	'91/03/01  BY Ockeghem
#
#	Use, e.g., `make LIBDIR=D:\CABEZON', if `CLIB.LIB' is present in an
#	other than the current directory.
#
.SUFFIXES: .obj .pas	# For Borland MAKE, comment this line

.pas.obj :
	cab /c /j $<

LINK = LLD -L$(LIBDIR)

cabx.exe : CAB1.obj CBALLOC.obj CBDUMP.obj CBERROR.obj CBEVAL.obj \
	   CBEXGEN1.obj CBEXGEN2.obj CBEXGEN3.obj CBEXGEN4.obj CBEXPR.obj \
	   CBFLUSH.obj CBGEN1.obj CBGEN2.obj CBGEN3.obj CBGEN4.obj CBINIT.obj \
	   CBLEX.obj CBLEX1.obj CBLEX2.obj CBMODULE.obj CBPROC.obj \
	   CBSTATE.obj CBTABLE.obj CBTYPE.obj CBSTD.obj CBLABEL.obj cbcom.obj
	$(LINK) @cab1.lnk

CAB1.OBJ CBALLOC.OBJ CBCOM.OBJ CBDUMP.OBJ CBERROR.OBJ CBEVAL.OBJ \
CBEXGEN1.OBJ CBEXGEN2.OBJ CBEXGEN3.OBJ CBEXGEN4.OBJ CBEXPR.OBJ \
CBFLUSH.OBJ CBGEN1.OBJ CBGEN2.OBJ CBGEN3.OBJ CBGEN4.OBJ CBINIT.OBJ \
CBLABEL.OBJ CBLEX.OBJ CBLEX1.OBJ CBLEX2.OBJ CBMODULE.OBJ CBPROC.OBJ \
CBSTATE.OBJ CBSTD.OBJ CBTABLE.OBJ CBTYPE.OBJ : cbcom.pas

clean:
	del *.map
	del *.obj

veryclean : clean
	del cabx.exe
